Update server.properties
kaboomserver/server pull request #130
Opened 2024-06-10 23:02 UTC by NatsukiORG

2024-06-13 15:11 UTC, evallll commented
May I ask what is the purpose or reason behind disabling command blocks? As far as I am concerned, it is an integral part of kaboom to be able to use command blocks, this wouldn't do very good for the anarchy side of things and would break a lot of player bots which rely on command blocks.

2024-06-13 15:19 UTC, IuCC123 commented
I don't think this is a great idea, this ruins the point of Kaboom.

2024-06-13 15:58 UTC, vanquishes commented
😂😂😂😂

2024-06-14 12:19 UTC, B2RT0SZM77 commented
bad idea

2024-06-15 09:47 UTC, oie1 commented
bad

2024-06-16 04:00 UTC, Parker2991 commented
the hell is the point in this lmao

2024-06-17 03:55 UTC, Dinhero21 reviewed
no

2024-06-23 19:00 UTC, OptimisticDeving requested changes

2024-06-23 19:00 UTC, OptimisticDeving commented on server.properties
> +enable-command-block=false
Revert this change :pray:

2024-06-23 19:50 UTC, closed without merging